#include "TObject.h"

#ifndef ND__TTrueVertex_h
#define ND__TTrueVertex_h
namespace ND {
    class TTrueVertex;
} // end of namespace.

#include "TLorentzVector.h"

namespace ND {
    class TTrueVertex : public TObject {
        
    public:
        // Nested classes declaration.
        
    public:
        // Data Members.
        TLorentzVector Position;    //
        Int_t          ID;          //
        double         Pur;         //
        double         Eff;         //
        
        TTrueVertex();
        TTrueVertex(const TTrueVertex & );
        virtual ~TTrueVertex();
        
        ClassDef(TTrueVertex,2); // Generated by MakeProject.
    };
} // namespace
#endif
